apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 2.15.0
  name: kube-state-metrics
  namespace: kube-system
spec:
  type: NodePort  # 👈 Exposes service externally
  ports:
    - name: http-metrics
      port: 8080
      targetPort: http-metrics
      nodePort: 30080  # 👈 Choose a port between 30000-32767
    - name: telemetry
      port: 8081
      targetPort: telemetry
      nodePort: 30082  # 👈 Choose a port
  selector:
    app.kubernetes.io/name: kube-state-metrics
