apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5000
      nodePort: 30050
  externalIPs:
    - 192.168.49.2
