apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: frontend
          image: ghcr.io/raflibaihaqi/booking-frontend:latest
          imagePullPolicy: Always
          
          ports:
            - containerPort: 8080
          env:
            - name: VITE_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: VITE_API_BASE_URL

            - name: VITE_STRIPE_PUB_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: VITE_STRIPE_PUB_KEY
