apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: your-dockerhub-username/frontend:latest
          ports:
            - containerPort: 80
      env:
        - name: VITE_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: VITE_API_BASE_URL

        - name: VITE_STRIPE_PUB_KEY
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: VITE_STRIPE_PUB_KEY
