apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 80
      nodePort: 32310
  type: NodePort
  externalIPs:
    - 192.168.49.2