export const hotelTypes = [
    "Hotel",
    "Motel",
    "Resort",
    "Inn",
    "Hostel",
    "Guest House",
    "Bed & Breakfast",
    "Boutique Hotel",
    "Villa",
    "Apartment",
    "Cottage",
    "Cabin",
    "Lodge",
    "Bungalow",
    "Hostal",
    "Ryokan",
    "Pension",
    "Aparthotel",
    "Vacation Home",
    "Holiday Park",
    "Residence",
    "Townhouse",
    "Chalet",
    "Farm Stay",
    "Boat",
    "Tent",
    "Capsule Hotel",
    "Campsite",
    "Other",
];

export const hotelFacilities = [
    "Free WiFi",
    "Parking",
    "Airport Shuttle",
    "Family Rooms",
    "Non-Smoking Rooms",
    "Outdoor Pool",
    "Spa",
    "Fitness Center",
  ];