name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
          contents: read
          packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v6
        with:
          context: ./backend  
          push: true
          tags: |
            ghcr.io/raflibaihaqi/booking-backend:latest
            ghcr.io/raflibaihaqi/booking-backend:${{ github.sha }}

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend  
          push: true
          tags: |
            ghcr.io/raflibaihaqi/booking-frontend:latest
            ghcr.io/raflibaihaqi/booking-frontend:${{ github.sha }}

      - name: Set Up SSH Key
        run: |
           mkdir -p ~/.ssh
           echo "${{ secrets.VPS_SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
           chmod 600 ~/.ssh/id_ed25519
           ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts
           ls -la ~/.ssh
           cat ~/.ssh/id_ed25519

      - name: Deploy to Kubernetes via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 rafli@${{ secrets.VPS_IP }} << 'EOF'
            set -e  
            export KUBECONFIG=~/.kube/config

            echo "🔥 Syncing latest K8s manifests..."
            rm -rf /home/rafli/Hotel-Booking-App/k8s
            cd /home/rafli/Hotel-Booking-App
            git fetch origin main
            git reset --hard origin/main   
            git pull origin main 

            echo "🔥 Deleting Old Kubernetes Deployments..."
            kubectl delete deployment backend --ignore-not-found=true
            kubectl delete deployment frontend --ignore-not-found=true
            kubectl delete pod --all
            kubectl delete service backend-service --ignore-not-found=true
            kubectl delete service frontend-service --ignore-not-found=true

            echo "🔑 Creating Kubernetes Secret for GitHub Container Registry (GHCR)..."
            kubectl create secret docker-registry ghcr-secret \
              --docker-server=ghcr.io \
              --docker-username=${{ secrets.GHCR_USERNAME }} \
              --docker-password=${{ secrets.GHCR_TOKEN }} \
              --docker-email=${{ secrets.GHCR_EMAIL }} \
              --dry-run=client -o yaml | kubectl apply -f -

            echo "🚀 Creating Kubernetes Secrets..."
            kubectl create secret generic app-secrets \
              --from-literal=MONGODB_CONNECTION_STRING="${{ secrets.MONGODB_CONNECTION_STRING }}" \
              --from-literal=JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}" \
              --from-literal=CLOUDINARY_CLOUD_NAME="${{ secrets.CLOUDINARY_CLOUD_NAME }}" \
              --from-literal=CLOUDINARY_API_KEY="${{ secrets.CLOUDINARY_API_KEY }}" \
              --from-literal=CLOUDINARY_API_SECRET="${{ secrets.CLOUDINARY_API_SECRET }}" \
              --from-literal=STRIPE_API_KEY="${{ secrets.STRIPE_API_KEY }}" \
              --from-literal=VITE_STRIPE_PUB_KEY="${{ secrets.VITE_STRIPE_PUB_KEY }}" \
              --dry-run=client -o yaml | kubectl apply -f -

            echo "📦 Deploying New Kubernetes Configuration..."
            kubectl apply -f /home/rafli/Hotel-Booking-App/k8s/app-config.yaml --force
            kubectl apply -f /home/rafli/Hotel-Booking-App/k8s/backend-deploy.yaml --force
            kubectl apply -f /home/rafli/Hotel-Booking-App/k8s/frontend-deploy.yaml --force
            kubectl apply -f /home/rafli/Hotel-Booking-App/k8s/backend-service.yaml --force
            kubectl apply -f /home/rafli/Hotel-Booking-App/k8s/frontend-service.yaml --force

            echo "✅ Deployment Completed Successfully!"
          EOF


