name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [ubuntu-latest. large]

    permissions:
          contents: read
          packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v6
        with:
          context: ./backend  
          push: true
          tags: |
            ghcr.io/raflibaihaqi/booking-backend:latest
            ghcr.io/raflibaihaqi/booking-backend:${{ github.sha }}

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend  
          push: true
          tags: |
            ghcr.io/raflibaihaqi/booking-frontend:latest
            ghcr.io/raflibaihaqi/booking-frontend:${{ github.sha }}

      


      - name: Set Up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

      - name: Debug SSH Key
        run: |
          ls -la ~/.ssh
          cat ~/.ssh/id_ed25519
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no rafli@${{ secrets.VPS_IP }} "echo SSH Connection Success"
          
      - name: Deploy to Kubernetes via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 rafli@${{ secrets.VPS_IP }} << 'EOF'
            export KUBECONFIG=~/.kube/config
            kubectl create secret generic app-secrets \
              --from-literal=MONGODB_CONNECTION_STRING="${{ secrets.MONGODB_CONNECTION_STRING }}" \
              --from-literal=JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}" \
              --from-literal=CLOUDINARY_CLOUD_NAME="${{ secrets.CLOUDINARY_CLOUD_NAME }}" \
              --from-literal=CLOUDINARY_API_KEY="${{ secrets.CLOUDINARY_API_KEY }}" \
              --from-literal=CLOUDINARY_API_SECRET="${{ secrets.CLOUDINARY_API_SECRET }}" \
              --from-literal=STRIPE_API_KEY="${{ secrets.STRIPE_API_KEY }}" \
              --from-literal=VITE_STRIPE_PUB_KEY="${{ secrets.VITE_STRIPE_PUB_KEY }}" \
              --dry-run=client -o yaml | kubectl apply -f -

            kubectl apply -f /home/rafli/Hotel-Booking-App/k8s/app-config.yaml
            kubectl apply -f /home/rafli/Hotel-Booking-App/k8s/backend-deploy.yaml
            kubectl apply -f /home/rafli/Hotel-Booking-App/k8s/frontend-deploy.yaml
            kubectl apply -f /home/rafli/Hotel-Booking-App/k8s/backend-service.yaml
            kubectl apply -f /home/rafli/Hotel-Booking-App/k8s/frontend-service.yaml
          EOF

